on: [push, pull_request]

name: Continuous Integration

jobs:
  build-test-deploy:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: yarn format-check
      - run: yarn lint

      - run: echo "Deploying to GitHub Pages if on the main branch..."
      - if: contains('refs/heads/main', github.ref)
        run: yarn bundle
      - name: Deploy to GitHub Pages
        if: contains('refs/heads/main', github.ref)
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
